### ISSUE TITLE
Automocking?

### ISSUE THREAD

**Issue by zth** [oscarhealth/graphql-mock-factory#1]
Hey @jnak !

This is looking great. I know it can get messy, but have you thought anything about auto-generated mocks? I know it's problematic, but I think it'd have quite a lot of value in a lot of projects. One of the projects I'm in for example has quite a large schema that evolves rather quickly. While I do agree with the approach of hand-writing a lot of the mocks, it'd be nice to be able to autogenerate _some_ of the mocks. 

What's your stance on this? Maybe this is something you'd prefer to be implemented outside of this project?

**Comment by jnak** [comment]
Hello @zth, thanks for starting the first issue. 

Yes I agree that there are cases where it makes more sense to auto-generate some of the mocks. For example, there is not much value in manually mocking relay connections. 

There is a currently a hook that lets you do just that. You can pass a [`getBaseMockForField`](getBaseMockForField) callback function that will be called for each schema field unless a base mock is already defined. It is not documented yet but you can look at [`getBaseMockForRelayField`](https://github.com/oscarhealth/graphql-mock-factory/blob/31248decd2a937628eb416466b55d025c893286f/src/mockRelay.js#L67-L89) and some of the [tests](https://github.com/oscarhealth/graphql-mock-factory/blob/master/src/__tests__/mockRelay.test.js#L167-L171) for it.

If you want to define a default mock for an Int, you can do something like that:
```js
function getBaseMocks(parentType, field) {   
  if (field.type == GraphQLInt) {
    return () => 2;  // Replace with your base mock for Int
  }
 ... 
}

const server = mockServer(schemaDefinition, mocks, getBaseMocks);
```
I'm definitely open to the idea of making it easier in the future. For now, I wanted to make the hook as flexible as possible so we can experiment with it and decide what we want do down the road. From an API perspective, it's easier to relax constrain than to add new ones. 

In the meantime, I would be fine adding a `getDefaultBaseMocks` function that defines some sensible default mocks. Do you have any recommendation for the base mocks based on your use case?

By the way we currently only require base mocks for fields that are queried. So assuming you don't query all your schema in a single test, it should be manageable to gradually add base mocks. And the good thing is that the more base mocks there are, the less you need to add new base mocks in subsequent tests.

**Comment by jnak** [comment]
Hello @zth,

Just a heads that I added a way to automatically mock all common fields. I also enabled by default so it's easier for people to get started. That said, it's completely optional and can be easily disabled at a later point. The change is included in the `0.0.1` version on npm.

Btw I also spent quite a bit of time to fully document everything. It should be a lot easier now to use this lib. Please let me know if anything can be improved.

Cheers,
J

**Comment by jnak** [comment]
Just released `0.3.0` that also mocks all Relay connections by default :) I added documentation on how to disable / extend this if needed. 

Let me know how that works for you.

**Comment by zth** [comment]
Looking great @jnak! I'm struggling to find time to properly test this in a project, but as soon as I do, I'll get back to you with my experience!

**Comment by jnak** [comment]
Closing this since automocking has been available for a year at this point. Feel free to re-open if you run into issues with it.
