### ISSUE TITLE
Storybook & fs dependency

### ISSUE THREAD

**Issue by bokelley** [oscarhealth/graphql-mock-factory#4]
Great library, and thank you for sharing it. I had the idea today to use my mockServer as a backend for storybook, as some of our stories are pretty complex and it's a pain to try to figure out how to pass mocked Relay call all the way through the component hierarchy. However, because `graphql-mock-factory` depends on `casual`, it has a dependency on `fs`. I tried flipping to `casual-browserify` but it caused (sic!) some weird behavior. I saw a code comment about switching to `faker` when 5.0.0 comes out, but who knows when that will be. Is there a particular feature you're waiting for there? (Happy to PR a change but didn't want to do it if there was a reason you were waiting)

**Comment by jnak** [comment]
Hi, 

alas I don't remember the exact reason behind this comment. I don't see any problem switching to the current version of `faker` if it already covers all of our existing use cases. Please feel free send a PR - I'll be quick to review / merge it. 

Thanks!

**Comment by jnak** [comment]
Closing now that https://github.com/oscarhealth/graphql-mock-factory/pull/5 is merged. Thanks for sending a PR.
